@startuml
skinparam classAttributeIconsize 0
class Championnat
{
-nom : string
+ajouterEquipe(Equipe : Equipe) : void
+nombreEquipe() : int
}
class Equipe
{
-nom : string
-nombreLikes : int
+incrementerNombreLikes(): void
}
Equipe --> "0..*" Championnat
@enduml